AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create VPC, subnets, security groups, route tables, and EC2 instances.

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: vpc_group8

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC # Tham chiếu đến VPC đã tạo
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: us-east-1a
      Tags:
        - Key: Name
          Value: public_subnet # Tên Subnet

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC # Tham chiếu đến VPC đã tạo
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: us-east-1b
      Tags:
        - Key: Name
          Value: private_subnet # Tên Subnet

Outputs:
  VpcId:
    Value: !Ref VPC
    Description: The ID of the VPC

  PublicSubnetId:
    Value: !Ref PublicSubnet
    Description: The ID of the public subnet

  PrivateSubnetId:
    Value: !Ref PrivateSubnet
    Description: The ID of the private subnet
